# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Committees"
  url = "committees-webpage/"
  weight = 20

[[main]]
  name = "Events"
  url = "event-webpage/"
  weight = 30

[[main]]
  name = "Calendar"
  url = "calendar/"
  weight = 50

[[main]]
  name = "Meet the Team"
  url = "board/#blank"
  weight = 60

[[main]]
  name = "Contact"
  url = "contact/#blank"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
